spring:
  application:
    name: To-Do-List

  datasource:
    url: jdbc:postgresql://localhost:5432/todo_db
    username: postgres
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: "FNKJDSHFSHFKJHFJHSGJKSHGKJSHGKJHGFKJDFH"
  expiration: 3600000
